-- Inserindo dados na tabela categories
INSERT INTO categories (name, description, active) VALUES 
('Musical', 'Eventos relacionados à música, como shows, concertos e festivais musicais.', true),
('Educacional', 'Eventos educacionais, como palestras, workshops e cursos.', true),
('Artes Visuais', 'Eventos focados em artes visuais, como exposições, instalações e galerias.', true),
('Cinema', 'Eventos relacionados ao cinema, como exibições, festivais e debates.', true),
('Literatura', 'Eventos literários, como lançamentos de livros, saraus e clubes de leitura.', true),
('Teatro', 'Eventos teatrais, como peças, espetáculos e monólogos.', true),
('Esportivo', 'Eventos esportivos, como campeonatos e maratonas.', true),
('Religioso', 'Eventos religiosos, como encontros, cultos e retiros.', true),
('Tecnológico', 'Eventos tecnológicos, como hackathons, meetups e conferências.', true);

-- Inserindo dados na tabela event_types
INSERT INTO event_types (name, description, active) VALUES 
('Palestra', 'Eventos focados em uma apresentação ou discussão sobre um tema específico.', true),
('Workshop', 'Eventos interativos, onde os participantes aprendem na prática.', true),
('Curso', 'Eventos educativos mais longos, focados em um aprendizado aprofundado.', true),
('Seminário', 'Eventos acadêmicos ou profissionais com diversas apresentações.', true),
('Congresso', 'Eventos de grande escala, com múltiplos temas e sessões.', true),
('Conferência', 'Eventos com palestras e debates sobre um tema específico.', true),
('Exposição', 'Eventos que exibem obras de arte, produtos ou projetos.', true),
('Festival', 'Eventos com diversas atrações, como shows, palestras e exposições.', true),
('Feira', 'Eventos comerciais com expositores e visitantes.', true),
('Encontro', 'Eventos sociais ou profissionais para networking e interação.', true),
('Show', 'Eventos musicais com apresentações ao vivo.', true),
('Culto', 'Eventos religiosos com orações, cânticos e pregações.', true),
('Retiro', 'Eventos religiosos ou espirituais com atividades de reflexão e meditação.', true),
('Campeonato', 'Eventos esportivos com competições e premiações.', true),
('Maratona', 'Eventos esportivos com corridas de longa distância.', true),
('Hackathon', 'Eventos tecnológicos com desafios de programação.', true),
('Meetup', 'Eventos informais para networking e troca de conhecimento.', true),
('Clube de Leitura', 'Eventos literários para discussão de livros e autores.', true),
('Lançamento', 'Eventos literários para lançamento de livros e bate-papo com autores.', true),
('Sarau', 'Eventos literários com música, poesia e outras manifestações artísticas.', true),
('Peça', 'Eventos teatrais com encenações de textos dramáticos.', true),
('Espetáculo', 'Eventos teatrais com apresentações artísticas e musicais.', true),
('Monólogo', 'Eventos teatrais com um único ator em cena.', true),
('Exibição', 'Eventos de cinema com projeção de filmes.', true),
('Festival de Cinema', 'Eventos de cinema com exibição de filmes e debates.', true);

-- Inserindo dados na tabela event_statuses
INSERT INTO event_statuses (name, description, active) VALUES 
('Em Andamento', 'Eventos que estão ocorrendo no momento.', true),
('Cancelado', 'Eventos que foram cancelados antes da realização.', true),
('Finalizado', 'Eventos que já ocorreram e foram concluídos.', true),
('Agendado', 'Eventos programados para ocorrer em uma data futura.', true),
('Adiado', 'Eventos que foram adiados para outra data.', true);

INSERT INTO events (name, description, address_id, link_maps, status_id, type_id, category_id, start_date, end_date, link, participants_number, banner, price, active) VALUES
-- Eventos Musicais
('Concerto de Primavera', 
 'Um concerto ao ar livre com a Orquestra Sinfônica.', 
 NULL, 
 'https://maps.google.com/concerto-primavera', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Show'), 
 (SELECT id FROM categories WHERE name = 'Musical'), 
 '2025-03-20', 
 '2025-03-20', 
 'https://eventos.com/concerto-primavera', 
 500, 
 'banner_concerto.jpg', --urls de imagens
 0.00, 
 true),

('Festival de Jazz na Praia', 
 'Um festival de jazz com músicos renomados.', 
 NULL, 
 'https://maps.google.com/festival-jazz', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Festival'), 
 (SELECT id FROM categories WHERE name = 'Musical'), 
 '2025-05-01', 
 '2025-05-03', 
 'https://eventos.com/festival-jazz', 
 800, 
 'banner_festival_jazz.jpg', 
 20.00, 
 true),

-- Eventos Educacionais
('Palestra sobre Sustentabilidade Urbana', 
 'Discussão sobre soluções para ambientes urbanos sustentáveis.', 
 NULL, 
 'https://maps.google.com/palestra-sustentabilidade', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Palestra'), 
 (SELECT id FROM categories WHERE name = 'Educacional'), 
 '2025-06-10', 
 '2025-06-10', 
 'https://eventos.com/palestra-sustentabilidade', 
 300, 
 'banner_sustentabilidade.jpg', 
 10.00, 
 true),

('Workshop de Programação Python', 
 'Evento prático para iniciantes em programação com Python.', 
 NULL, 
 'https://maps.google.com/workshop-python', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Workshop'), 
 (SELECT id FROM categories WHERE name = 'Educacional'), 
 '2025-07-15', 
 '2025-07-15', 
 'https://eventos.com/workshop-python', 
 50, 
 'banner_python.jpg', 
 15.00, 
 true),

-- Eventos Tecnológicos
('Hackathon IMD 2025', 
 'Maratona de programação para resolver desafios reais.', 
 NULL, 
 'https://maps.google.com/hackathon-imd-2025', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Hackathon'), 
 (SELECT id FROM categories WHERE name = 'Tecnológico'), 
 '2025-05-15', 
 '2025-05-17', 
 'https://eventos.com/hackathon-imd-2025', 
 100, 
 'banner_hackathon.jpg', 
 NULL, 
 true),

('Conferência de IA e Machine Learning', 
 'Discussão sobre as tendências e avanços na área de IA.', 
 NULL, 
 'https://maps.google.com/conferencia-ia', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Conferência'), 
 (SELECT id FROM categories WHERE name = 'Tecnológico'), 
 '2025-08-20', 
 '2025-08-22', 
 'https://eventos.com/conferencia-ia', 
 150, 
 'banner_ia.jpg', 
 50.00, 
 true),

-- Eventos Literários
('Clube de Leitura: Grandes Clássicos', 
 'Encontro mensal para discutir clássicos da literatura.', 
 NULL, 
 'https://maps.google.com/clube-leitura', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Clube de Leitura'), 
 (SELECT id FROM categories WHERE name = 'Literatura'), 
 '2025-03-01', 
 '2025-03-01', 
 'https://eventos.com/clube-leitura', 
 30, 
 'banner_clube_leitura.jpg', 
 NULL, 
 true),

('Lançamento de Livro: "O Futuro é Agora"', 
 'Evento com o autor e sessão de autógrafos.', 
 NULL, 
 'https://maps.google.com/lancamento-livro', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Lançamento'), 
 (SELECT id FROM categories WHERE name = 'Literatura'), 
 '2025-04-10', 
 '2025-04-10', 
 'https://eventos.com/lancamento-livro', 
 100, 
 'banner_livro.jpg', 
 5.00, 
 true),

-- Eventos Teatrais
('Peça Teatral: Hamlet', 
 'Apresentação do clássico de Shakespeare.', 
 NULL, 
 'https://maps.google.com/hamlet', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Peça'), 
 (SELECT id FROM categories WHERE name = 'Teatro'), 
 '2025-05-30', 
 '2025-05-30', 
 'https://eventos.com/hamlet', 
 150, 
 'banner_hamlet.jpg', 
 25.00, 
 true),

('Monólogo: "A Voz do Silêncio"', 
 'Apresentação intimista com temas emocionantes.', 
 NULL, 
 'https://maps.google.com/voz-silencio', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Monólogo'), 
 (SELECT id FROM categories WHERE name = 'Teatro'), 
 '2025-06-15', 
 '2025-06-15', 
 'https://eventos.com/voz-silencio', 
 80, 
 'banner_monologo.jpg', 
 10.00, 
 true),

-- Outros Eventos Variados
('Feira de Negócios Sustentáveis', 
 'Evento com expositores e palestras sobre sustentabilidade.', 
 NULL, 
 'https://maps.google.com/feira-negocios', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Feira'), 
 (SELECT id FROM categories WHERE name = 'Educacional'), 
 '2025-07-01', 
 '2025-07-03', 
 'https://eventos.com/feira-negocios', 
 200, 
 'banner_feira.jpg', 
 30.00, 
 true),

('Maratona Esportiva 2025', 
 'Corrida com diferentes categorias para todas as idades.', 
 NULL, 
 'https://maps.google.com/maratona-2025', 
 (SELECT id FROM event_statuses WHERE name = 'Agendado'), 
 (SELECT id FROM event_types WHERE name = 'Maratona'), 
 (SELECT id FROM categories WHERE name = 'Esportivo'), 
 '2025-09-10', 
 '2025-09-10', 
 'https://eventos.com/maratona-2025', 
 500, 
 'banner_maratona.jpg', 
 50.00, 
 true);
